# codemagic.yaml

workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      # KHÔNG CẦN android_signing nữa, nên đã xóa đi
      groups:
        - swipenews
      vars:
        PACKAGE_NAME: "com.example.swipenews"
      flutter: stable
      
    cache:
      cache_paths:
        - $HOME/.pub-cache
        
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Setup Firebase configuration
        script: |
          chmod +x scripts/setup_firebase.sh
          ./scripts/setup_firebase.sh
      
      - name: Force set Gradle memory options
        script: |
          echo "org.gradle.jvmargs=-Xmx4g" >> "$CM_BUILD_DIR/android/gradle.properties"
          echo "--- Current gradle.properties ---"
          cat "$CM_BUILD_DIR/android/gradle.properties"
          echo "---------------------------------"    
      - name: Flutter analyze
        script: |
          flutter analyze
          
      - name: Build Android APK (Debug)
        script: |
          # Đổi sang build file APK với chế độ debug
          flutter build apk --debug
          
    artifacts:
      # Cập nhật đường dẫn để lấy file APK debug
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/**/outputs/**/mapping.txt
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic # Cấu hình trong Codemagic UI
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.swipenews
      groups:
        - swipenews # Chứa biến môi trường cho Firebase
      vars:
        APP_ID: 1234567890 # Thay bằng App Store Connect App ID của bạn
      flutter: stable
      xcode: latest
      cocoapods: default
      
    # Thêm cache cho cả Flutter và CocoaPods
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $CM_BUILD_DIR/ios/Pods
        
    scripts:
      - name: Setup Firebase configuration
        script: |
          # Bước 1: Tạo tệp firebase_options.dart TRƯỚC TIÊN.
          chmod +x scripts/setup_firebase.sh
          ./scripts/setup_firebase.sh
          
      - name: Get Flutter packages
        script: |
          # Bước 2: Lấy packages để tạo Podfile chính xác.
          flutter packages pub get
          
      - name: Install pods
        script: |
          # Bước 3: Cài đặt các thư viện native cho iOS.
          find . -name "Podfile" -execdir pod install \;
          
      - name: Set up code signing settings on Xcode project
        script: |
          # Bước 4: Cấu hình signing trên dự án Xcode.
          xcode-project use-profiles
          
      - name: Flutter build ipa
        script: |
          # Bước 5: Build file IPA với số build tự động tăng.
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        # Thay 'group_name' bằng tên nhóm Beta thực tế trên TestFlight của bạn
        beta_groups:
          - group_name 