# codemagic.yaml
workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference # Tạo trong Codemagic UI
      groups:
        - firebase_credentials # Tạo group trong Codemagic UI
      vars:
        PACKAGE_NAME: "com.example.swipenews"
      flutter: stable
      
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
          
      - name: Setup Firebase configuration
        script: |
          # Make script executable
          chmod +x scripts/setup_firebase.sh
          # Run setup script
          ./scripts/setup_firebase.sh
          
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Flutter analyze
        script: |
          flutter analyze
          
      - name: Build APK
        script: |
          flutter build apk --release
          
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic # Configure trong UI
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.swipenews
      groups:
        - firebase_credentials
      vars:
        APP_ID: 1234567890 # Your App Store Connect app ID
      flutter: stable
      
    scripts:
      - name: Setup Firebase configuration
        script: |
          chmod +x scripts/setup_firebase.sh
          ./scripts/setup_firebase.sh
          
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
          
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
          
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group_name